// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yapryntsev/go-musthave-metrics/internal/repository (interfaces: MetricRepository)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/repository_mock.go -package mocks . MetricRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/yapryntsev/go-musthave-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricRepository is a mock of MetricRepository interface.
type MockMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricRepositoryMockRecorder is the mock recorder for MockMetricRepository.
type MockMetricRepositoryMockRecorder struct {
	mock *MockMetricRepository
}

// NewMockMetricRepository creates a new mock instance.
func NewMockMetricRepository(ctrl *gomock.Controller) *MockMetricRepository {
	mock := &MockMetricRepository{ctrl: ctrl}
	mock.recorder = &MockMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricRepository) EXPECT() *MockMetricRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricRepository) Get(ctx context.Context, mID, mType string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, mID, mType)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricRepositoryMockRecorder) Get(ctx, mID, mType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricRepository)(nil).Get), ctx, mID, mType)
}

// GetAll mocks base method.
func (m *MockMetricRepository) GetAll(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMetricRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMetricRepository)(nil).GetAll), ctx)
}

// Set mocks base method.
func (m *MockMetricRepository) Set(ctx context.Context, metric models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockMetricRepositoryMockRecorder) Set(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMetricRepository)(nil).Set), ctx, metric)
}

// SetBatch mocks base method.
func (m *MockMetricRepository) SetBatch(ctx context.Context, metrics []*models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBatch indicates an expected call of SetBatch.
func (mr *MockMetricRepositoryMockRecorder) SetBatch(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatch", reflect.TypeOf((*MockMetricRepository)(nil).SetBatch), ctx, metrics)
}
