package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type templatePayload struct {
	Package string
	Method  string
}

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package {{.Package}}

{{.Method}}
`

var tmpl = template.Must(template.New("reset").Parse(templateStr))

func main() {
	fset := token.NewFileSet()
	err := forEachFile(
		fset,
		func(file *ast.File, node ast.Node) bool {
			x, ok := node.(*ast.GenDecl)
			if !ok || x.Tok != token.TYPE || strings.TrimSpace(x.Doc.Text()) != "generate:reset" {
				return true
			}

			payload := templatePayload{
				Package: file.Name.String(),
				Method:  prepareTemplateMethod(x),
			}

			path := fset.Position(file.Package).Filename
			comp := strings.Split(path, "/")

			fileName := fmt.Sprintf("%s.gen.go", strings.Split(comp[len(comp)-1], ".")[0])
			outputPath := strings.Replace(path, comp[len(comp)-1], fileName, 1)

			outputFile, err := os.OpenFile(outputPath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0664)
			if err != nil {
				panic(err)
			}

			if err := tmpl.Execute(outputFile, payload); err != nil {
				panic(err)
			}

			return false
		},
	)

	if err != nil {
		panic(err)
	}
}

func forEachFile(fset *token.FileSet, f func(file *ast.File, node ast.Node) bool) error {
	pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedFiles}, "./...")
	if err != nil {
		return fmt.Errorf("failed to load package info: %w", err)
	}

	for _, pkg := range pkgs {
		for _, fp := range pkg.GoFiles {
			file, err := parser.ParseFile(fset, fp, nil, parser.ParseComments)
			if err != nil {
				return fmt.Errorf("failed to parse file: %w", err)
			}

			ast.Inspect(
				file, func(node ast.Node) bool {
					return f(file, node)
				},
			)
		}
	}

	return nil
}

func prepareTemplateMethod(node *ast.GenDecl) string {
	var buf bytes.Buffer

	for _, spec := range node.Specs {
		ts, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			continue
		}

		receiver := "v"

		_, _ = fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", receiver, ts.Name.Name)
		_, _ = fmt.Fprintf(&buf, "\tif %s == nil { return }\n\n", receiver)

		for _, field := range st.Fields.List {
			for _, name := range field.Names {
				writeResetLogic(&buf, receiver, name.Name, field.Type)
			}
		}
		_, _ = fmt.Fprintf(&buf, "}")
	}

	return buf.String()
}

func writeResetLogic(buf *bytes.Buffer, receiver string, fieldName string, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			_, _ = fmt.Fprintf(buf, "\t%s.%s = \"\"\n", receiver, fieldName)
			return
		case "bool":
			_, _ = fmt.Fprintf(buf, "\t%s.%s = false\n", receiver, fieldName)
			return
		case "byte":
			_, _ = fmt.Fprintf(buf, "\t%s.%s = 0\n", receiver, fieldName)
			return
		}

		if strings.HasPrefix(t.Name, "uint") {
			_, _ = fmt.Fprintf(buf, "\t%s.%s = 0\n", receiver, fieldName)
		} else if strings.HasPrefix(t.Name, "int") {
			_, _ = fmt.Fprintf(buf, "\t%s.%s = 0\n", receiver, fieldName)
		} else if strings.HasPrefix(t.Name, "float") {
			_, _ = fmt.Fprintf(buf, "\t%s.%s = 0.0\n", receiver, fieldName)
		} else {
			_, _ = fmt.Fprintf(
				buf,
				"\tif rst, ok := any(%s.%s).(interface { Reset() }); ok {\n\t\trst.Reset()\n\t}\n",
				receiver,
				fieldName,
			)
		}
	case *ast.ArrayType:
		_, _ = fmt.Fprintf(buf, "\t%s.%s = %s.%s[:0]\n", receiver, fieldName, receiver, fieldName)
	case *ast.MapType:
		_, _ = fmt.Fprintf(buf, "\tclear(%s.%s)\n", receiver, fieldName)
	case *ast.StarExpr:
		_, _ = fmt.Fprintf(buf, "\t%s.%s = nil\n", receiver, fieldName)
	case *ast.SelectorExpr:
		_, _ = fmt.Fprintf(
			buf,
			"\tif rst, ok := any(%s.%s).(interface { Reset() }); ok {\n\t\trst.Reset()\n\t}\n",
			receiver,
			fieldName,
		)
	}
}
